### ISSUE TITLE
sort by likes from a keyword

### ISSUE THREAD

**Issue by simon300000** [kokororin/pixiv.moe#49]
Marco Pazto <pastopasto@hotmail.it>
is reaching me with email, suggesting a new function.

> Hello! Many thanks for the reply!
I wanted to know if it was possible to sort a keyword (like, lets say "Kasumi") for how many likes (hearts / favorites) they got in the site.
I don't really get the sorting of pixiv.moe, is not by date, is not by likes... How is it sorted?
Anyway, it would be ultra awesome to have a "sort by favorites" option... Can you add that?

**Comment by simon300000** [comment]
@shugen002

**Comment by shugen002** [comment]
Http 200 ok

**Comment by shugen002** [comment]
Simon
simon30002021@icloud.com

> 下面是被转发的邮件：
> 
> 发件人: Marco Pazto <pastopasto@hotmail.it>
> 主题: R: Pixiv Moe Question
> 日期: 2020年9月15日 GMT+2 下午5:58:03
> 收件人: Simon Ouyang <simon30002021@icloud.com>
> 
> I'm just wondering how pixiv.moe sort the images when you search a keyword tho.
> Is not by date or likes, so I wonder how it sort em... A sort by option would be the best!
> Anyway, let me know if there will be any updates, and thanks ♥
> 
> Da: Simon Ouyang <simon30002021@icloud.com>
> Inviato: martedì 15 settembre 2020 17:16
> A: Marco Pazto <pastopasto@hotmail.it>
> Oggetto: Re: Pixiv Moe Question
>  
> Okay, I’ll open an issue.
> 
> Actually not really, I believe the daily rank is provided by pixiv.net, and I guess they don’t provide all time ranking, but I am not sure, haha.
> 
> simon3000
> simon30002021@icloud.com
> 
>> 在 15.09.2020，下午4:36，Marco Pazto <pastopasto@hotmail.it> 写道：
>> 
>> ﻿
>> Sure! Feel free to share it, and update me / link me everything about it if you want.
>> I can't help much with programming, but if you need a tester, or if I can help in some way, let me know.
>> I guess if it sort by daily ranking, it could be added a "all times ranking", right?
>> 
>> Da: Simon Ouyang <simon30002021@icloud.com>
>> Inviato: martedì 15 settembre 2020 16:32
>> A: Marco Pazto <pastopasto@hotmail.it>
>> Oggetto: Re: Pixiv Moe Question
>>  
>> Hi, it seems like pixiv’s daily ranking. I am not capable to add this function, but I could open an issue about this and share with other developers, would you be okay sharing your email in the issue?
>> 
>> simon3000
>> simon30002021@icloud.com
>> 
>>> 在 15.09.2020，下午4:15，Marco Pazto <pastopasto@hotmail.it> 写道：
>>> 
>>> ﻿
>>> Hello! Many thanks for the reply!
>>> I wanted to know if it was possible to sort a keyword (like, lets say "Kasumi") for how many likes (hearts / favorites) they got in the site.
>>> I don't really get the sorting of pixiv.moe, is not by date, is not by likes... How is it sorted?
>>> Anyway, it would be ultra awesome to have a "sort by favorites" option... Can you add that?
>>> 
>>> Da: Simon <simon30002021@icloud.com>
>>> Inviato: martedì 15 settembre 2020 16:09
>>> A: Marco Pazto <pastopasto@hotmail.it>
>>> Oggetto: Re: Pixiv Moe Question
>>>  
>>> Hi,
>>> 
>>> what do you mean by “popularity”? There is “Ranking” on the side which I believe is sort by popularity.
>>> 
>>> Also, maybe consider raising an issue here, https://github.com/LoveLiveSunshine/pixiv.moe/issues <https://github.com/LoveLiveSunshine/pixiv.moe/issues> , I am not really a maintainer of this site.
>>> <粘贴的图形-1.png>
>>> 
>>> 
>>> Simon
>>> simon30002021@icloud.com <mailto:simon30002021@icloud.com>
>>> 
>>>> 15.09.2020 下午1:28，Marco Pazto <pastopasto@hotmail.it <mailto:pastopasto@hotmail.it>> 写道：
>>>> 
>>>> Hello! I love Pixiv.Moe, but it don't sort by popularity properly...
>>>> Any way to fix it?

**Comment by simon300000** [comment]
Simon
simon30002021@icloud.com

> 下面是被转发的邮件：
> 
> 发件人: Marco Pazto <pastopasto@hotmail.it>
> 主题: R: Pixiv Moe Question
> 日期: 2020年9月15日 GMT+2 下午5:58:03
> 收件人: Simon Ouyang <simon30002021@icloud.com>
> 
> I'm just wondering how pixiv.moe sort the images when you search a keyword tho.
> Is not by date or likes, so I wonder how it sort em... A sort by option would be the best!
> Anyway, let me know if there will be any updates, and thanks ♥
> 
> Da: Simon Ouyang <simon30002021@icloud.com>
> Inviato: martedì 15 settembre 2020 17:16
> A: Marco Pazto <pastopasto@hotmail.it>
> Oggetto: Re: Pixiv Moe Question
>  
> Okay, I’ll open an issue.
> 
> Actually not really, I believe the daily rank is provided by pixiv.net, and I guess they don’t provide all time ranking, but I am not sure, haha.
> 
> simon3000
> simon30002021@icloud.com
> 
>> 在 15.09.2020，下午4:36，Marco Pazto <pastopasto@hotmail.it> 写道：
>> 
>> ﻿
>> Sure! Feel free to share it, and update me / link me everything about it if you want.
>> I can't help much with programming, but if you need a tester, or if I can help in some way, let me know.
>> I guess if it sort by daily ranking, it could be added a "all times ranking", right?
>> 
>> Da: Simon Ouyang <simon30002021@icloud.com>
>> Inviato: martedì 15 settembre 2020 16:32
>> A: Marco Pazto <pastopasto@hotmail.it>
>> Oggetto: Re: Pixiv Moe Question
>>  
>> Hi, it seems like pixiv’s daily ranking. I am not capable to add this function, but I could open an issue about this and share with other developers, would you be okay sharing your email in the issue?
>> 
>> simon3000
>> simon30002021@icloud.com
>> 
>>> 在 15.09.2020，下午4:15，Marco Pazto <pastopasto@hotmail.it> 写道：
>>> 
>>> ﻿
>>> Hello! Many thanks for the reply!
>>> I wanted to know if it was possible to sort a keyword (like, lets say "Kasumi") for how many likes (hearts / favorites) they got in the site.
>>> I don't really get the sorting of pixiv.moe, is not by date, is not by likes... How is it sorted?
>>> Anyway, it would be ultra awesome to have a "sort by favorites" option... Can you add that?
>>> 
>>> Da: Simon <simon30002021@icloud.com>
>>> Inviato: martedì 15 settembre 2020 16:09
>>> A: Marco Pazto <pastopasto@hotmail.it>
>>> Oggetto: Re: Pixiv Moe Question
>>>  
>>> Hi,
>>> 
>>> what do you mean by “popularity”? There is “Ranking” on the side which I believe is sort by popularity.
>>> 
>>> Also, maybe consider raising an issue here, https://github.com/LoveLiveSunshine/pixiv.moe/issues <https://github.com/LoveLiveSunshine/pixiv.moe/issues> , I am not really a maintainer of this site.
>>> <粘贴的图形-1.png>
>>> 
>>> 
>>> Simon
>>> simon30002021@icloud.com <mailto:simon30002021@icloud.com>
>>> 
>>>> 15.09.2020 下午1:28，Marco Pazto <pastopasto@hotmail.it <mailto:pastopasto@hotmail.it>> 写道：
>>>> 
>>>> Hello! I love Pixiv.Moe, but it don't sort by popularity properly...
>>>> Any way to fix it?

**Comment by J-Almeida** [comment]
Could you explain how to sort by popularity? It's listed in the Readme as on of the app's features and this issue is closed but I could not find how to do it
