### ISSUE TITLE
Error - 403

### ISSUE THREAD

**Issue by Kadantte** [kokororin/pixiv.moe#60]
Why Am I getting this after I hosted my own [deployment](https://pixiv.usui.moe/) of your front-end?

![image](https://user-images.githubusercontent.com/11579313/109093268-ed34d280-76cc-11eb-8767-37762459208a.png)

**Comment by kokororin** [comment]
It has block by CORS policy. Should proxy the backend  for your own, like Nginx.

**Comment by Kadantte** [comment]
I did it now [proxy](https://pixiv-proxy.vercel.app/session) But how I'm supposed to return these headers? `X-Access-Token` and `X-Kotori-Token`.

![image](https://user-images.githubusercontent.com/11579313/109569987-2d65cd80-7a9e-11eb-901d-13a0eb4844c6.png)

**Comment by kokororin** [comment]
I don't know how you proxy, but with Nginx it's simple.

```conf
    location /api/ {
        proxy_pass https://api.pixiv.moe/;
        proxy_ssl_server_name on;
        proxy_set_header Host api.pixiv.moe;
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }
```
Then can request the "session" api as "https://pixiv.usui.moe/api/session" instead of "https://api.pixiv.moe/session".
And the base url should be modified in [config file](https://github.com/kokororin/pixiv.moe/blob/master/src/config/index.ts)

**Comment by Kadantte** [comment]
Well, I use Fastify to do it!
index.js
```js
'use strict'

const fastify = require('fastify')
const path = require('path')

function build () {
  const server = fastify({
    logger: true
})

server.register(require('fastify-cors'))
server.register(require('fastify-http-proxy'), {
  upstream: 'https://api.pixiv.moe',
  http2: false // optional
})
return server
}
module.exports = build
```
/api/serverless.js
```js
'use strict'

const build = require('../index')

const server = build()

module.exports = async function (req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  await server.ready()
  server.server.emit('request', req, res)
}
```
vercel.json
```json
{
  "version": 2,
  "builds": [
    {
      "src": "api/serverless.js",
      "use": "@vercel/node",
      "config": {
        "helpers": false
      }
    }
  ],
  "routes": [
    {
      "src": "/.*",
      "dest": "/api/serverless.js"
    }
  ]
}
```

**Comment by kokororin** [comment]
Our API has no geoblock

**Comment by Kadantte** [comment]
Thanks for your reply and help, I try it with my proxy on local it works I dunno why on local works but it doesn't after deploying it on vercel! I'll look into it and see what is wrong on deployment or I might just test on gh-pages!

**Comment by Kadantte** [comment]
I'll close this for now till I get the time to do my own investigations!
