### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by Ruriko** [kokororin/pixiv.moe#65]
Can I have the full install instructions on how to install the script for public access? I'm running Ubuntu 20.04 64bit and I've installed git, nodejs, yarn. Then I ran the following commands
```
git clone https://github.com/kokororin/pixiv.moe
$ cd pixiv.moe
$ yarn
$ npm start
```
but it gave an error. I've attached a screenshot to show you the error. Is there any other dependencies that I need to install?
![putty](https://user-images.githubusercontent.com/5670857/111860643-9c935b00-8994-11eb-98c8-ab011458e27b.png)

**Comment by kokororin** [comment]
Duplicated as #56.
`npm start` is for development. For production use, `npm run build`

**Comment by Ruriko** [comment]
@kokororin where do I go to view the site? I tried going to my domain but it doesn't look like it's installed there

**Comment by Ruriko** [comment]
Are there anymore steps to do after running `npm run build` ? cause I installed it under my domain directory and it doesn't detect any index file http://adoreanime.com/pixiv.moe/ I'm using nginx as my webserver.
