### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Ruriko** [kokororin/pixiv.moe#67]
I installed the script via Docker but when I try to view my site it says 403 This page is not available in your area.
This is how I installed:

```
docker build -t pix github.com/kokororin/pixiv.moe
docker run -p 8080:80 -d pix
```
then I changed nginx config to this
```
server {
  listen 80;
  server_name adoreanime.com;

location / {
    proxy_pass  http://localhost:8080;
  }

  location /api/ {
    proxy_pass https://api.pixiv.moe/;
    proxy_ssl_server_name on;
    proxy_set_header Host api.pixiv.moe;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
  }

  location ~* .(ico|gif|bmp|jpg|jpeg|png|js|css) {
    expires 30d;
  }

}
```

How to fix this? my site is http://adoreanime.com/

**Comment by kokororin** [comment]
502 Bad Gateway

**Comment by Ruriko** [comment]
can you check again I just rebooted the vps and the site just loads (・ω・) forever

**Comment by kokororin** [comment]
(index):1 GET http://adoreanime.com/app.b64028b89bbb5e8e056f.js net::ERR_ABORTED 404 (Not Found)
js file 404

**Comment by Ruriko** [comment]
I fixed the missing js file by changing nginx conf to this
```
server {
  listen 80;
  server_name adoreanime.com;

location / {
    proxy_pass  http://localhost:8080;
  }

  location /api/ {
    proxy_pass https://api.pixiv.moe/;
    proxy_ssl_server_name on;
    proxy_set_header Host api.pixiv.moe;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
  }

}
```
but I don't know how to fix the 403 error. In chrome console it says: 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.pixiv.moe/session. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by kokororin** [comment]
Your website is requesting to `https://api.pixiv.moe/` not `http://adoreanime.com/api`, have you changed the source code?

**Comment by Ruriko** [comment]
Where do I go to change the source code?

**Comment by kokororin** [comment]
Please pull the latest code and re-build
