### ISSUE TITLE
Animated pics are static on moe

### ISSUE THREAD

**Issue by Ruriko** [kokororin/pixiv.moe#68]
It seems like any animated pics on pixiv.net are static on pixiv.moe. Here's one example:
https://www.pixiv.net/en/artworks/82337676
https://pixiv.moe/illust/82337676

**Comment by kokororin** [comment]
fixed in 69b5323

**Comment by Ruriko** [comment]
It works now but all the animated pics that are R-18 don't work it just shows the loading circle forever
