### ISSUE TITLE
R-18 animated pics don't load

### ISSUE THREAD

**Issue by Ruriko** [kokororin/pixiv.moe#69]
All animated pics that are R-18 don't load. It just shows a loading circle. Here's an example
https://www.pixiv.net/en/artworks/89047963
https://pixiv.moe/illust/89047963

**Comment by Ruriko** [comment]
do you plan to fix this bug?

**Comment by kokororin** [comment]
Already fixed. Our server cannot fetch R-18 animated pics, so it will fallback to static.
