### ISSUE TITLE
[Feature Request] Add Profile Page

### ISSUE THREAD

**Issue by Ruriko** [kokororin/pixiv.moe#84]
Can you make a profile page for the artist that displays all their drawings and include their social links twitter, pawoo, homepage etc if they have one. Also display their avatar if they don't have one use the set default. Rather than having a link to their pixiv profile I think it's better to just add the profile page to your script since the user probably can't access pixiv in their country?

**Comment by kokororin** [comment]
This api is available.
`/v2/user/33333`
