### ISSUE TITLE
Redirect direct images

### ISSUE THREAD

**Issue by Ruriko** [kokororin/pixiv.moe#90]
Is it possible if you can redirect direct image urls to the image page? for example https://api.pixiv.moe/image/i.pximg.net/c/600x1200_90/img-master/img/2021/12/30/01/18/57/95122414_p0_master1200.jpg@progressive.webp redirect to https://pixiv.moe/illust/95122414

**Comment by kokororin** [comment]
Sorry, i cannot understand

**Comment by Ruriko** [comment]
If user hotlink image and then they try to directly visit image url it should redirect to illust page

**Comment by kokororin** [comment]
If you do this, users will not be able to download pictures through other tools
